<?php

/**
 * FEAT-054 — canonical primary facts and curated derived metrics (single catalogue).
 */
return [
    'catalog_version' => 'v8-fundamentals-catalog-1',
    'primary_facts' => [
        'revenue' => ['label' => 'Revenue', 'group' => 'income', 'statement_type' => 'income_statement'],
        'operating_profit' => ['label' => 'Operating profit', 'group' => 'income', 'statement_type' => 'income_statement'],
        'ebit' => ['label' => 'EBIT', 'group' => 'income', 'statement_type' => 'income_statement'],
        'ebitda' => ['label' => 'EBITDA', 'group' => 'income', 'statement_type' => 'income_statement'],
        'net_income' => ['label' => 'Net income', 'group' => 'income', 'statement_type' => 'income_statement'],
        'eps' => ['label' => 'EPS', 'group' => 'income', 'statement_type' => 'income_statement'],
        'eps_diluted' => ['label' => 'EPS (diluted)', 'group' => 'income', 'statement_type' => 'income_statement'],
        'interest_income' => ['label' => 'Interest income', 'group' => 'bank', 'statement_type' => 'income_statement'],
        'interest_expense' => ['label' => 'Interest expense', 'group' => 'bank', 'statement_type' => 'income_statement'],
        'net_interest_income' => ['label' => 'Net interest income', 'group' => 'bank', 'statement_type' => 'income_statement'],
        'total_assets' => ['label' => 'Total assets', 'group' => 'balance', 'statement_type' => 'balance_sheet'],
        'total_liabilities' => ['label' => 'Total liabilities', 'group' => 'balance', 'statement_type' => 'balance_sheet'],
        'equity' => ['label' => 'Equity', 'group' => 'balance', 'statement_type' => 'balance_sheet'],
        'debt' => ['label' => 'Debt', 'group' => 'balance', 'statement_type' => 'balance_sheet'],
        'long_term_debt' => ['label' => 'Long-term debt', 'group' => 'balance', 'statement_type' => 'balance_sheet'],
        'cash_and_equivalents' => ['label' => 'Cash & equivalents', 'group' => 'balance', 'statement_type' => 'balance_sheet'],
        'trade_receivables' => ['label' => 'Trade receivables', 'group' => 'balance', 'statement_type' => 'balance_sheet'],
        'inventory' => ['label' => 'Inventory', 'group' => 'balance', 'statement_type' => 'balance_sheet'],
        'current_assets' => ['label' => 'Current assets', 'group' => 'balance', 'statement_type' => 'balance_sheet'],
        'current_liabilities' => ['label' => 'Current liabilities', 'group' => 'balance', 'statement_type' => 'balance_sheet'],
        'property_plant_equipment' => ['label' => 'Property, plant & equipment', 'group' => 'balance', 'statement_type' => 'balance_sheet'],
        'capital_work_in_progress' => ['label' => 'Capital work in progress', 'group' => 'balance', 'statement_type' => 'balance_sheet'],
        'gross_npa' => ['label' => 'Gross NPA', 'group' => 'bank', 'statement_type' => 'balance_sheet'],
        'gross_npa_ratio' => ['label' => 'Gross NPA ratio', 'group' => 'bank', 'statement_type' => 'balance_sheet'],
        'net_npa' => ['label' => 'Net NPA', 'group' => 'bank', 'statement_type' => 'balance_sheet'],
        'net_npa_ratio' => ['label' => 'Net NPA ratio', 'group' => 'bank', 'statement_type' => 'balance_sheet'],
        'capital_adequacy_ratio' => ['label' => 'Capital adequacy ratio', 'group' => 'bank', 'statement_type' => 'balance_sheet'],
        'provisions' => ['label' => 'Provisions', 'group' => 'bank', 'statement_type' => 'balance_sheet'],
        'net_interest_margin' => ['label' => 'Net interest margin', 'group' => 'bank', 'statement_type' => 'income_statement'],
        'operating_cash_flow' => ['label' => 'Operating cash flow', 'group' => 'cash_flow', 'statement_type' => 'cash_flow'],
        'investing_cash_flow' => ['label' => 'Investing cash flow', 'group' => 'cash_flow', 'statement_type' => 'cash_flow'],
        'financing_cash_flow' => ['label' => 'Financing cash flow', 'group' => 'cash_flow', 'statement_type' => 'cash_flow'],
        'capital_expenditure' => ['label' => 'Capital expenditure', 'group' => 'cash_flow', 'statement_type' => 'cash_flow'],
        'dividends_paid' => ['label' => 'Dividends paid', 'group' => 'cash_flow', 'statement_type' => 'cash_flow'],
        'shares_outstanding' => ['label' => 'Shares outstanding', 'group' => 'balance', 'statement_type' => 'balance_sheet'],
        'promoter_holding' => ['label' => 'Promoter holding', 'group' => 'ownership', 'statement_type' => 'ownership'],
        'fii_holding' => ['label' => 'FII/FPI holding', 'group' => 'ownership', 'statement_type' => 'ownership'],
        'dii_holding' => ['label' => 'DII holding', 'group' => 'ownership', 'statement_type' => 'ownership'],
        'public_holding' => ['label' => 'Public holding', 'group' => 'ownership', 'statement_type' => 'ownership'],
        'promoter_pledge' => ['label' => 'Promoter pledge', 'group' => 'ownership', 'statement_type' => 'ownership'],
    ],
    'derived_metrics' => [
        'revenue' => ['label' => 'Revenue (TTM)', 'default_basis' => 'ttm', 'requires_price' => false, 'kind' => 'flow_ttm'],
        'net_income' => ['label' => 'Net income (TTM)', 'default_basis' => 'ttm', 'requires_price' => false, 'kind' => 'flow_ttm'],
        'eps' => ['label' => 'EPS (TTM)', 'default_basis' => 'ttm', 'requires_price' => false, 'kind' => 'per_share'],
        'free_cash_flow' => ['label' => 'Free cash flow (TTM)', 'default_basis' => 'ttm', 'requires_price' => false, 'kind' => 'derived_flow'],
        'market_cap' => ['label' => 'Market cap', 'default_basis' => 'ttm', 'requires_price' => true, 'kind' => 'currency_level'],
        'enterprise_value' => ['label' => 'Enterprise value', 'default_basis' => 'ttm', 'requires_price' => true, 'kind' => 'currency_level'],
        'roe' => ['label' => 'ROE (TTM)', 'default_basis' => 'ttm', 'requires_price' => false, 'kind' => 'ratio_percent'],
        'operating_margin' => ['label' => 'Operating margin (TTM)', 'default_basis' => 'ttm', 'requires_price' => false, 'kind' => 'ratio_percent'],
        'net_margin' => ['label' => 'Net margin (TTM)', 'default_basis' => 'ttm', 'requires_price' => false, 'kind' => 'ratio_percent'],
        'debt_equity' => ['label' => 'Debt / equity', 'default_basis' => 'ttm', 'requires_price' => false, 'kind' => 'ratio'],
        'net_debt' => ['label' => 'Net debt', 'default_basis' => 'ttm', 'requires_price' => false, 'kind' => 'level'],
        'ebitda' => ['label' => 'EBITDA (TTM)', 'default_basis' => 'ttm', 'requires_price' => false, 'kind' => 'flow_ttm'],
        'debt_to_ebitda' => ['label' => 'Debt / EBITDA', 'default_basis' => 'ttm', 'requires_price' => false, 'kind' => 'ratio'],
        'interest_coverage' => ['label' => 'Interest coverage', 'default_basis' => 'ttm', 'requires_price' => false, 'kind' => 'ratio'],
        'fcf_margin' => ['label' => 'FCF margin (TTM)', 'default_basis' => 'ttm', 'requires_price' => false, 'kind' => 'ratio_percent'],
        'fcf_yield' => ['label' => 'FCF yield (TTM)', 'default_basis' => 'ttm', 'requires_price' => true, 'kind' => 'ratio_percent'],
        'dividend_yield' => ['label' => 'Dividend yield (TTM)', 'default_basis' => 'ttm', 'requires_price' => true, 'kind' => 'ratio_percent'],
        'payout_ratio' => ['label' => 'Payout ratio (TTM)', 'default_basis' => 'ttm', 'requires_price' => false, 'kind' => 'ratio_percent'],
        'pe' => ['label' => 'P/E (TTM)', 'default_basis' => 'ttm', 'requires_price' => true, 'kind' => 'valuation'],
        'pb' => ['label' => 'P/B', 'default_basis' => 'ttm', 'requires_price' => true, 'kind' => 'valuation'],
        'revenue_growth_yoy' => ['label' => 'Revenue growth (YoY)', 'default_basis' => 'quarterly_yoy', 'requires_price' => false, 'kind' => 'growth'],
        'gross_npa_ratio' => ['label' => 'Gross NPA ratio', 'default_basis' => 'quarterly', 'requires_price' => false, 'kind' => 'bank_ratio', 'sector' => 'bank'],
        'net_npa_ratio' => ['label' => 'Net NPA ratio', 'default_basis' => 'quarterly', 'requires_price' => false, 'kind' => 'bank_ratio', 'sector' => 'bank'],
        'capital_adequacy_ratio' => ['label' => 'Capital adequacy ratio', 'default_basis' => 'quarterly', 'requires_price' => false, 'kind' => 'bank_ratio', 'sector' => 'bank'],
        'net_interest_margin' => ['label' => 'Net interest margin', 'default_basis' => 'ttm', 'requires_price' => false, 'kind' => 'bank_ratio', 'sector' => 'bank'],
    ],
    'investor_summary_metric_ids' => [
        'market_cap',
        'enterprise_value',
        'pe',
        'pb',
        'roe',
        'operating_margin',
        'net_margin',
        'revenue_growth_yoy',
        'debt_equity',
        'free_cash_flow',
        'fcf_yield',
        'dividend_yield',
    ],
    /*
     * FEAT-054 §13 / §11 — chart presentation defaults (daily valuation series aggregated for display).
     */
    'chart_defaults' => [
        'default_range' => '5y',
        'valuation_default_frequency' => 'monthly',
        'flow_default_frequency' => 'quarterly',
    ],
];
