<?php

/**
 * FEAT-057 feature registry metadata (V8 foundation). Training code remains in MlTrainingDatasetBuilder.
 */
return [
    'registry_version' => 'v8-registry-11',
    'preprocessing' => [
        'version' => 'v8-preprocessing-1',
        'missing_values' => 'median_with_missingness_flags',
        'fitted_on' => 'training_partition_only',
        'categorical_unknown' => '__unknown',
        'outliers' => [
            'version' => 'v8-outlier-policy-1',
            'method' => 'training_quantile_clip',
            'lower_quantile' => 0.01,
            'upper_quantile' => 0.99,
            'features' => [
                'debt_equity',
                'revenue_growth_proxy',
                'eps_growth_yoy',
                'net_income_growth_yoy',
                'net_debt_equity',
                'pe_ratio',
                'pb_ratio',
            ],
            'fitted_on' => 'training_partition_only',
        ],
    ],
    'features' => [
        'relative_strength_1m' => [
            'kind' => 'numeric',
            'group' => 'market_relative',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Stock 1m return minus benchmark 1m return (%).',
        ],
        'relative_strength_3m' => [
            'kind' => 'numeric',
            'group' => 'market_relative',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Stock 3m return minus benchmark 3m return (%).',
        ],
        'relative_strength_6m' => [
            'kind' => 'numeric',
            'group' => 'market_relative',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Stock 6m return minus benchmark 6m return (%).',
        ],
        'benchmark_return_3m' => [
            'kind' => 'numeric',
            'group' => 'market_regime',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Benchmark 63-trading-day return (%).',
        ],
        'benchmark_return_6m' => [
            'kind' => 'numeric',
            'group' => 'market_regime',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Benchmark 126-trading-day return (%).',
        ],
        'benchmark_trend_score' => [
            'kind' => 'numeric',
            'group' => 'market_regime',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Benchmark close vs 20-day SMA distance (%).',
        ],
        'momentum_score' => [
            'kind' => 'numeric',
            'group' => 'price_action',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => '21-trading-day price return (%).',
        ],
        'price_return_1m' => [
            'kind' => 'numeric',
            'group' => 'price_action',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => '21-trading-day price return (%), explicit 1m column.',
        ],
        'price_return_3m' => [
            'kind' => 'numeric',
            'group' => 'price_action',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => '63-trading-day price return (%).',
        ],
        'price_return_6m' => [
            'kind' => 'numeric',
            'group' => 'price_action',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => '126-trading-day price return (%).',
        ],
        'price_return_12m' => [
            'kind' => 'numeric',
            'group' => 'price_action',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => '252-trading-day price return (%).',
        ],
        'trend_score' => [
            'kind' => 'numeric',
            'group' => 'price_action',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Close vs 20-day SMA distance (%).',
        ],
        'trend_score_ma50' => [
            'kind' => 'numeric',
            'group' => 'price_action',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Close vs 50-day SMA distance (%).',
        ],
        'trend_score_ma200' => [
            'kind' => 'numeric',
            'group' => 'price_action',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Close vs 200-day SMA distance (%).',
        ],
        'benchmark_realized_volatility_20d' => [
            'kind' => 'numeric',
            'group' => 'market_regime',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Benchmark 20-day annualized realized volatility (%).',
        ],
        'roe' => [
            'kind' => 'numeric',
            'group' => 'fundamentals',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'TTM return on equity at as-of (fundamentals PIT).',
        ],
        'debt_equity' => [
            'kind' => 'numeric',
            'group' => 'fundamentals',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'TTM debt/equity at as-of.',
        ],
        'revenue_growth_proxy' => [
            'kind' => 'numeric',
            'group' => 'fundamentals',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Quarterly revenue YoY growth at as-of.',
        ],
        'eps_growth_yoy' => [
            'kind' => 'numeric',
            'group' => 'fundamentals',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Quarterly EPS YoY growth at as-of.',
        ],
        'net_income_growth_yoy' => [
            'kind' => 'numeric',
            'group' => 'fundamentals',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Quarterly net income YoY growth at as-of.',
        ],
        'ocf_to_net_income_ratio' => [
            'kind' => 'numeric',
            'group' => 'fundamentals',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'TTM operating cash flow / TTM net income.',
        ],
        'operating_margin' => [
            'kind' => 'numeric',
            'group' => 'fundamentals',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'TTM operating profit / TTM revenue (%).',
        ],
        'net_margin' => [
            'kind' => 'numeric',
            'group' => 'fundamentals',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'TTM net income / TTM revenue (%).',
        ],
        'fcf_margin' => [
            'kind' => 'numeric',
            'group' => 'fundamentals',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'TTM free cash flow / TTM revenue (%).',
        ],
        'realized_volatility_20d' => [
            'kind' => 'numeric',
            'group' => 'price_action',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Annualized realized volatility from 20-day log returns (%).',
        ],
        'realized_volatility_63d' => [
            'kind' => 'numeric',
            'group' => 'price_action',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Annualized realized volatility from 63-day log returns (%).',
        ],
        'volatility_ratio_20_63' => [
            'kind' => 'numeric',
            'group' => 'volatility',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Ratio of 20-day to 63-day realized volatility.',
        ],
        'volume_trend_20d' => [
            'kind' => 'numeric',
            'group' => 'volume',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Recent 5-day average volume vs prior 15-day average (% change).',
        ],
        'net_debt_equity' => [
            'kind' => 'numeric',
            'group' => 'fundamentals',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Net debt / equity at as-of (fundamentals PIT).',
        ],
        'current_drawdown_pct' => [
            'kind' => 'numeric',
            'group' => 'price_action',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Drawdown from trailing peak close (%).',
        ],
        'pe_ratio' => [
            'kind' => 'numeric',
            'group' => 'valuation',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Price / TTM EPS at as-of.',
        ],
        'pb_ratio' => [
            'kind' => 'numeric',
            'group' => 'valuation',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Price / book value at as-of.',
        ],
        'distance_52w_high_pct' => [
            'kind' => 'numeric',
            'group' => 'price_action',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Close distance from trailing 52-week high (%).',
        ],
        'volume_ratio_20d' => [
            'kind' => 'numeric',
            'group' => 'price_action',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Session volume divided by trailing 20-day average volume.',
        ],
        'distance_20d_high_pct' => [
            'kind' => 'numeric',
            'group' => 'price_action',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Close distance from trailing 20-day high (%).',
        ],
        'atr_pct_14' => [
            'kind' => 'numeric',
            'group' => 'volatility',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => '14-day ATR as % of close.',
        ],
        'consolidation_width_20d_pct' => [
            'kind' => 'numeric',
            'group' => 'pattern',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => '20-day high-low range width as % of close.',
        ],
        'range_position_20d' => [
            'kind' => 'numeric',
            'group' => 'pattern',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Close position within 20-day range (0–100).',
        ],
        'candle_body_to_range_1d' => [
            'kind' => 'numeric',
            'group' => 'pattern',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Absolute close-to-close move divided by session high-low range.',
        ],
        'downside_volatility_20d' => [
            'kind' => 'numeric',
            'group' => 'volatility',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Annualized volatility of negative daily log returns (20d window).',
        ],
        'up_day_ratio_20d' => [
            'kind' => 'numeric',
            'group' => 'price_action',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Fraction of up days in trailing 20 sessions.',
        ],
        'current_ratio' => [
            'kind' => 'numeric',
            'group' => 'fundamentals',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Current assets / current liabilities at as-of.',
        ],
        'gross_margin' => [
            'kind' => 'numeric',
            'group' => 'fundamentals',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'TTM gross profit / TTM revenue (%).',
        ],
        'gross_npa_ratio' => [
            'kind' => 'numeric',
            'group' => 'fundamentals_bank',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Latest GNPA ratio when reported (null for non-banks).',
        ],
        'net_npa_ratio' => [
            'kind' => 'numeric',
            'group' => 'fundamentals_bank',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Latest NNPA ratio when reported (null for non-banks).',
        ],
        'capital_adequacy_ratio' => [
            'kind' => 'numeric',
            'group' => 'fundamentals_bank',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Capital adequacy ratio when reported.',
        ],
        'net_interest_margin' => [
            'kind' => 'numeric',
            'group' => 'fundamentals_bank',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Reported NIM or TTM net interest income / TTM interest income (%).',
        ],
        'sector_relative_strength_3m' => [
            'kind' => 'numeric',
            'group' => 'sector_context',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Stock 3m return minus sector-peer median 3m return (%).',
            'tier' => 'challenger',
            'evidence_required' => true,
        ],
        'market_breadth_nifty' => [
            'kind' => 'numeric',
            'group' => 'market_regime',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Cross-sectional % of active equities above 20-day SMA.',
        ],
        'sector' => [
            'kind' => 'categorical',
            'group' => 'identity',
            'pit_safe' => true,
            'horizons' => ['1m', '3m', '6m'],
            'description' => 'Sector classification bucket.',
            'tier' => 'challenger',
            'evidence_required' => true,
        ],
    ],
];
