/**
 * Metadata-driven navigation catalog (flat).
 * Sidebar renders from this file only — no hardcoded menu trees in JSX.
 *
 * Top-level sidebar pages only (`showInSidebar: true`).
 * Editor / registry / settings sub-pages stay as internal routes (`showInSidebar: false`).
 *
 * Model fields:
 *   id, title, icon, route, group, order, parent, children (derived),
 *   badge, tag ('NEW'|'BETA'|null), disabled, external,
 *   showInSidebar, favouriteEligible,
 *   kind ('group'|'page'), permission (future), match (optional route matcher)
 */

import { ROUTES, pathEquals, pathStartsWith } from '../navigation/routes';

/** @typedef {'group'|'page'} NavKind */

/**
 * @typedef {object} NavItem
 * @property {string} id
 * @property {string} title
 * @property {string|null} [icon] Lucide icon name (e.g. "Gauge")
 * @property {string|null} [route]
 * @property {string|null} [group] Group id for pages
 * @property {number} order
 * @property {string|null} [parent]
 * @property {string[]|null} [children] Populated by buildNavigationTree
 * @property {string|number|null} [badge]
 * @property {'NEW'|'BETA'|string|null} [tag]
 * @property {boolean} [disabled]
 * @property {boolean} [external] Open `route` in a new tab
 * @property {boolean} showInSidebar
 * @property {boolean} favouriteEligible
 * @property {NavKind} kind
 * @property {string|null} [permission] Future gate key
 * @property {(pathname: string) => boolean} [match]
 */

/** @type {NavItem[]} */
export const NAVIGATION_CATALOG = [
    // ── Groups ──────────────────────────────────────────────
    {
        id: 'group-portfolio',
        title: 'Portfolio',
        icon: 'Briefcase',
        route: null,
        group: null,
        order: 10,
        parent: null,
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: false,
        kind: 'group',
        permission: null,
    },
    {
        id: 'group-market',
        title: 'Market',
        icon: 'Globe2',
        route: null,
        group: null,
        order: 20,
        parent: null,
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: false,
        kind: 'group',
        permission: null,
    },
    {
        id: 'group-trading',
        title: 'Trading',
        icon: 'Zap',
        route: null,
        group: null,
        order: 30,
        parent: null,
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: false,
        kind: 'group',
        permission: null,
    },
    {
        id: 'group-knowledge',
        title: 'Knowledge',
        icon: 'BookOpen',
        route: null,
        group: null,
        order: 40,
        parent: null,
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: false,
        kind: 'group',
        permission: null,
    },
    {
        id: 'group-administration',
        title: 'Administration',
        icon: 'Settings',
        route: null,
        group: null,
        order: 50,
        parent: null,
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: false,
        kind: 'group',
        permission: null,
    },

    // ── Portfolio pages ─────────────────────────────────────
    {
        id: 'dashboard',
        title: 'Dashboard',
        icon: 'Gauge',
        route: ROUTES.HOME,
        group: 'group-portfolio',
        order: 10,
        parent: 'group-portfolio',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathEquals(p, ROUTES.HOME),
    },
    {
        id: 'holdings',
        title: 'Holdings',
        icon: 'Briefcase',
        route: ROUTES.HOLDINGS,
        group: 'group-portfolio',
        order: 15,
        parent: 'group-portfolio',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.HOLDINGS),
    },
    {
        id: 'stock-prices',
        title: 'Stock Prices',
        icon: 'LineChart',
        route: null,
        group: 'group-portfolio',
        order: 16,
        parent: 'holdings',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: null,
        match: (p) => /^\/holdings\/[^/]+\/prices/.test(p),
    },
    {
        id: 'watchlist',
        title: 'Watchlist',
        icon: 'Eye',
        route: ROUTES.WATCHLIST,
        group: 'group-portfolio',
        order: 20,
        parent: 'group-portfolio',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.WATCHLIST),
    },
    {
        id: 'transactions',
        title: 'Transactions',
        icon: 'ArrowLeftRight',
        route: ROUTES.TRANSACTIONS,
        group: 'group-portfolio',
        order: 30,
        parent: 'group-portfolio',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.TRANSACTIONS),
    },
    {
        id: 'pending-execution',
        title: 'Pending Execution',
        icon: 'Hourglass',
        route: ROUTES.TRANSACTIONS_PENDING,
        group: 'group-portfolio',
        order: 31,
        parent: 'transactions',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.TRANSACTIONS_PENDING),
    },
    {
        id: 'closed-transactions',
        title: 'Closed Transactions',
        icon: 'SquareCheck',
        route: ROUTES.TRANSACTIONS_CLOSED,
        group: 'group-portfolio',
        order: 32,
        parent: 'transactions',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.TRANSACTIONS_CLOSED),
    },
    {
        id: 'portfolio-historical-holdings',
        title: 'Historical Holdings',
        icon: 'CalendarDays',
        route: ROUTES.PORTFOLIO_HISTORICAL_HOLDINGS,
        group: 'group-portfolio',
        order: 16,
        parent: 'group-portfolio',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.PORTFOLIO_HISTORICAL_HOLDINGS),
    },
    {
        id: 'portfolio-snapshots',
        title: 'Portfolio Snapshots',
        icon: 'History',
        route: ROUTES.PORTFOLIO_SNAPSHOTS,
        group: 'group-portfolio',
        order: 17,
        parent: 'group-portfolio',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.PORTFOLIO_SNAPSHOTS),
    },
    {
        id: 'cash',
        title: 'Cash',
        icon: 'Wallet',
        route: ROUTES.CASH,
        group: 'group-portfolio',
        order: 40,
        parent: 'group-portfolio',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.CASH),
    },
    {
        id: 'corporate-actions',
        title: 'Corporate Actions',
        icon: 'Building2',
        route: ROUTES.CORPORATE_ACTION,
        group: 'group-portfolio',
        order: 50,
        parent: 'group-portfolio',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.CORPORATE_ACTION),
    },

    // ── Market pages ────────────────────────────────────────
    {
        id: 'discovery',
        title: 'Discovery',
        icon: 'Search',
        route: ROUTES.CANDIDATES,
        group: 'group-market',
        order: 10,
        parent: 'group-market',
        children: null,
        badge: null,
        // V3: Discovery is not part of the recommendation workflow sidebar.
        // Direct /candidates remains for pipeline inspection.
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.CANDIDATES) || pathStartsWith(p, ROUTES.EVALUATIONS),
    },
    {
        id: 'stock-explorer',
        title: 'Stock Explorer',
        icon: 'LineChart',
        route: ROUTES.EXPLORER,
        group: 'group-market',
        order: 20,
        parent: 'group-market',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.EXPLORER),
    },
    {
        id: 'patterns',
        title: 'Patterns',
        icon: 'CandlestickChart',
        route: ROUTES.PATTERNS,
        group: 'group-market',
        order: 30,
        parent: 'group-market',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.PATTERNS),
    },
    {
        id: 'indices',
        title: 'Indices',
        icon: 'BarChart4',
        route: ROUTES.INDICES,
        group: 'group-market',
        order: 40,
        parent: 'group-market',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.INDICES),
    },
    {
        id: 'calendar',
        title: 'Calendar',
        icon: 'CalendarDays',
        route: ROUTES.CALENDAR,
        group: 'group-market',
        order: 50,
        parent: 'group-market',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.CALENDAR),
    },
    {
        id: 'market-depth',
        title: 'Market Depth',
        icon: 'Layers',
        route: ROUTES.MARKET_DEPTH,
        group: 'group-market',
        order: 60,
        parent: 'group-market',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.MARKET_DEPTH),
    },

    // ── Trading pages ───────────────────────────────────────
    {
        id: 'recommendations',
        title: 'Recommendations',
        icon: 'Lightbulb',
        route: ROUTES.RECOMMENDATIONS,
        group: 'group-trading',
        order: 10,
        parent: 'group-trading',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.RECOMMENDATIONS),
    },
    {
        id: 'review',
        title: 'Review',
        icon: 'ClipboardCheck',
        route: ROUTES.REVIEW,
        group: 'group-trading',
        order: 20,
        parent: 'group-trading',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.REVIEW),
    },
    {
        id: 'strategies',
        title: 'Strategies',
        icon: 'Target',
        route: ROUTES.STRATEGY,
        group: 'group-trading',
        order: 30,
        parent: 'group-trading',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        // Strategies editor only — Registry is its own sidebar item.
        match: (p) => pathStartsWith(p, ROUTES.STRATEGY) && !pathStartsWith(p, ROUTES.STRATEGY_REGISTRY),
    },
    {
        id: 'strategy-registry',
        title: 'Strategy Registry',
        icon: 'Library',
        route: ROUTES.STRATEGY_REGISTRY,
        group: 'group-trading',
        order: 31,
        parent: 'group-trading',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.STRATEGY_REGISTRY),
    },
    {
        id: 'backtests',
        title: 'Backtests',
        icon: 'LineChart',
        route: ROUTES.BACKTESTS,
        group: 'group-trading',
        order: 32,
        parent: 'group-trading',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.BACKTESTS),
    },
    {
        id: 'backtest-detail',
        title: 'Backtest Detail',
        icon: 'LineChart',
        route: null,
        group: 'group-trading',
        order: 33,
        parent: 'backtests',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: null,
        match: (p) => /^\/backtests\/[^/]+$/.test(p),
    },
    {
        id: 'screeners',
        title: 'Screeners',
        icon: 'Filter',
        route: ROUTES.SCREENERS,
        group: 'group-trading',
        order: 40,
        parent: 'group-trading',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        // Keep Screeners highlighted on editor + registry (internal) routes.
        match: (p) => pathStartsWith(p, ROUTES.SCREENERS),
    },
    {
        id: 'screener-registry',
        title: 'Screener Registry',
        icon: 'Library',
        route: ROUTES.SCREENER_REGISTRY,
        group: 'group-trading',
        order: 41,
        parent: 'screeners',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.SCREENER_REGISTRY),
    },
    {
        id: 'screener-editor',
        title: 'Screener Editor',
        icon: 'Pencil',
        route: null,
        group: 'group-trading',
        order: 42,
        parent: 'screeners',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: null,
        match: (p) => /^\/screeners\/[^/]+$/.test(p) && !pathStartsWith(p, ROUTES.SCREENER_REGISTRY),
    },

    // ── Knowledge pages ─────────────────────────────────────
    {
        id: 'knowledge-board',
        title: 'Knowledge Board',
        icon: 'BookOpen',
        route: ROUTES.KNOWLEDGE_BOARD,
        group: 'group-knowledge',
        order: 10,
        parent: 'group-knowledge',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.KNOWLEDGE_BOARD) && !pathStartsWith(p, ROUTES.KNOWLEDGE_TAGS),
    },
    {
        id: 'knowledge-tags',
        title: 'Knowledge Tags',
        icon: 'Tags',
        route: ROUTES.KNOWLEDGE_TAGS,
        group: 'group-knowledge',
        order: 20,
        parent: 'group-knowledge',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.KNOWLEDGE_TAGS),
    },

    // ── Administration pages ────────────────────────────────
    {
        id: 'settings',
        title: 'Settings',
        icon: 'Settings',
        route: ROUTES.SETTINGS_PORTFOLIO,
        group: 'group-administration',
        order: 10,
        parent: 'group-administration',
        children: null,
        badge: null,
        showInSidebar: true,
        favouriteEligible: true,
        kind: 'page',
        permission: null,
        // Keep Settings highlighted on admin/tool sub-routes (not listed in sidebar).
        match: (p) => pathStartsWith(p, ROUTES.SETTINGS),
    },
    {
        id: 'alert-policies',
        title: 'Alert Policies',
        icon: 'Bell',
        route: ROUTES.SETTINGS_ALERT_POLICIES,
        group: 'group-administration',
        order: 20,
        parent: 'settings',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.SETTINGS_ALERT_POLICIES),
    },
    {
        id: 'users',
        title: 'Users',
        icon: 'Users',
        route: ROUTES.SETTINGS_USERS,
        group: 'group-administration',
        order: 30,
        parent: 'settings',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: 'admin',
        match: (p) => pathStartsWith(p, ROUTES.SETTINGS_USERS),
    },
    {
        id: 'sync-logs',
        title: 'Sync Logs',
        icon: 'Library',
        route: ROUTES.SETTINGS_SYNC_LOGS,
        group: 'group-administration',
        order: 40,
        parent: 'settings',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: 'admin',
        match: (p) => pathStartsWith(p, ROUTES.SETTINGS_SYNC_LOGS),
    },
    {
        id: 'data-quality',
        title: 'Data Quality',
        icon: 'ShieldCheck',
        route: ROUTES.SETTINGS_DATA_QUALITY,
        group: 'group-administration',
        order: 50,
        parent: 'settings',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: 'admin',
        match: (p) => pathStartsWith(p, ROUTES.SETTINGS_DATA_QUALITY),
    },
    {
        id: 'indicator-registry',
        title: 'Indicator Registry',
        icon: 'Cpu',
        route: ROUTES.SETTINGS_INDICATORS,
        group: 'group-administration',
        order: 60,
        parent: 'settings',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: 'admin',
        match: (p) => pathStartsWith(p, ROUTES.SETTINGS_INDICATORS),
    },
    {
        id: 'admin-alerts',
        title: 'Admin Alerts',
        icon: 'Bell',
        route: ROUTES.SETTINGS_ADMIN_ALERTS,
        group: 'group-administration',
        order: 70,
        parent: 'settings',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: 'admin',
        match: (p) => pathStartsWith(p, ROUTES.SETTINGS_ADMIN_ALERTS),
    },
    {
        id: 'universe-price-sync',
        title: 'Universe Price Sync',
        icon: 'RefreshCw',
        route: ROUTES.SETTINGS_UNIVERSE_PRICE_SYNC,
        group: 'group-administration',
        order: 80,
        parent: 'settings',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: 'admin',
        match: (p) => pathStartsWith(p, ROUTES.SETTINGS_UNIVERSE_PRICE_SYNC),
    },
    {
        id: 'screener-registry-admin',
        title: 'Screener Registry',
        icon: 'Library',
        route: ROUTES.SETTINGS_SCREENER_REGISTRY,
        group: 'group-administration',
        order: 90,
        parent: 'settings',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: 'admin',
        match: (p) => pathStartsWith(p, ROUTES.SETTINGS_SCREENER_REGISTRY),
    },
    {
        id: 'strategy-registry-admin',
        title: 'Strategy Registry',
        icon: 'Library',
        route: ROUTES.SETTINGS_STRATEGY_REGISTRY,
        group: 'group-administration',
        order: 100,
        parent: 'settings',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: 'admin',
        match: (p) => pathStartsWith(p, ROUTES.SETTINGS_STRATEGY_REGISTRY),
    },
    {
        id: 'notification-history',
        title: 'Notification History',
        icon: 'Bell',
        route: ROUTES.NOTIFICATION_HISTORY,
        group: 'group-administration',
        order: 110,
        parent: 'settings',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.NOTIFICATION_HISTORY),
    },
    {
        id: 'portfolios',
        title: 'Portfolios',
        icon: 'Briefcase',
        route: ROUTES.PORTFOLIOS,
        group: 'group-administration',
        order: 120,
        parent: 'settings',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.PORTFOLIOS),
    },
    {
        id: 'profile',
        title: 'Profile',
        icon: 'Users',
        route: ROUTES.PROFILE,
        group: 'group-administration',
        order: 130,
        parent: 'settings',
        children: null,
        badge: null,
        showInSidebar: false,
        favouriteEligible: false,
        kind: 'page',
        permission: null,
        match: (p) => pathStartsWith(p, ROUTES.PROFILE),
    },
];
